"""
Converts .xrf files, which are generated by the XRF detector in MAXIMA, to .mca files, which are ingestible by PyMCA.

Notes
-----
- Currently, the function converts header lines by appending numbers directly.
- Future improvements should include more sophisticated metadata tracking 
  and robust handling of different XRF file formats. HP20251211
"""

def convert_xrf_to_mca(input_file, output_file):
    """
    Convert an XRF detector file (.xrf) to a PyMCA-compatible MCA file (.mca).

    This function reads counts from the input .xrf file, skipping header lines 
    and non-numeric entries, and writes them into an .mca file with the standard 
    PMCA format.

    Parameters
    ----------
    input_file : str
        Path to the input .xrf file.
    output_file : str
        Path where the output .mca file will be saved.

    Notes
    -----
    - Currently, this function uses a simple line-by-line parse and may need 
      updates for future XRF file format changes.
    - Counts are extracted from the second column of each data line.
    - Header lines containing 'xrf_data' are skipped.

    Examples
    --------
    >>> convert_xrf_to_mca("sample.xrf", "sample.mca")
    Converted sample.xrf -> sample.mca
    """
    with open(input_file, 'r') as f:
        lines = f.readlines()

    counts = []
    for line in lines:
        parts = line.strip().split()
        if len(parts) >= 2:
            if parts[0] == "xrf_data":
                continue
            try:
                count = int(float(parts[1]))
                counts.append(count)
            except ValueError:
                continue

    mca_lines = []
    mca_lines.append("<<PMCA SPECTRUM>>")
    mca_lines.append("VERSION: 1.0")
    mca_lines.append(f"CHANNELS: {len(counts)}")
    mca_lines.append("<<DATA>>")
    mca_lines.extend(str(count) for count in counts)
    mca_lines.append("<<END>>")

    with open(output_file, 'w') as f:
        f.write("\n".join(mca_lines))

    print(f"Converted {input_file} -> {output_file}")
